# Generated by Django 4.0.5 on 2022-06-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notifications_status',
            field=models.BooleanField(default=False),
        ),
    ]
