# Generated by Django 4.0.5 on 2022-06-18 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('discount_percent', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Waiting', 'Waiting')], default='Waiting', max_length=10)),
                ('is_processed', models.BooleanField(blank=True, default=False)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDiscountAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_actions', to='panels.discount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_actions', to='accounts.bankemployee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeediscountaction',
            constraint=models.UniqueConstraint(fields=('employee', 'discount'), name='unique_employee_discount'),
        ),
    ]
